CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    contrasenya VARCHAR(100) NOT NULL,
    ultimAcces DATE DEFAULT NULL,
    dataCreated TIMESTAMP CURRENT_TIMESTAMP,
    dataUpdated TIMESTAMP CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);