DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    contrasenya VARCHAR(100) NOT NULL,
    ultimAcces DATE DEFAULT NULL,
    dataCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);